# Generated by Django 5.2.5 on 2025-09-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auther', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('university', 'university'), ('admin', 'admin')], max_length=50),
        ),
    ]
